SELECT T3.ID, SUM(CHILD) AS CHILD_COUNT
FROM (
    SELECT T1.ID, IF(T2.ID IS NULL, 0, 1) AS CHILD
    FROM ECOLI_DATA T1
    LEFT JOIN ECOLI_DATA T2 ON T1.ID = T2.PARENT_ID
    ) AS T3
GROUP BY ID
ORDER BY ID
;