SELECT COUNT(*) AS FISH_COUNT
FROM (
    SELECT F.FISH_TYPE, FN.FISH_NAME
    FROM FISH_INFO F
    JOIN FISH_NAME_INFO FN ON F.FISH_TYPE = FN.FISH_TYPE 
    ) AS F2
    WHERE FISH_NAME IN ('BASS', 'SNAPPER')
;

