# SELECT COUNT(*) AS FISH_COUNT
# FROM (
#     SELECT F.FISH_TYPE, FN.FISH_NAME
#     FROM FISH_INFO F
#     JOIN FISH_NAME_INFO FN ON F.FISH_TYPE = FN.FISH_TYPE 
#     ) AS F2
#     WHERE FISH_NAME IN ('BASS', 'SNAPPER')
# ;

# SELECT SUM(X.CNT) AS FISHCOUNT
# FROM (
#     SELECT B.FISHNAME, COUNT(A.ID) AS CNT
#     FROM FISHINFO A JOIN FISHNAMEINFO B
#     ON A.FISHTYPE = B.FISHTYPE
#     AND B.FISHNAME IN ('BASS', 'SNAPPER')
#     GROUP BY B.FISH_NAME
# ) X

# SELECT COUNT(*) AS FISHCOUNT
# FROM FISHINFO A JOIN FISHNAMEINFO B ON A.FISHTYPE = B.FISHTYPE
# WHERE B.FISH_TYPE IN ('0', '1');

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO JOIN FISH_NAME_INFO USING (FISH_TYPE)
WHERE FISH_NAME IN ('BASS', 'SNAPPER');