SELECT FT.ID, FN.FISH_NAME, FT.LENGTH
FROM FISH_NAME_INFO AS FN
    JOIN (
        SELECT FISH_INFO.ID, F.FISH_TYPE, F.LENGTH
        FROM FISH_INFO
        JOIN (
            SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
            FROM FISH_INFO
            GROUP BY(FISH_TYPE)
            ) AS F
        ON F.FISH_TYPE = FISH_INFO.FISH_TYPE
        WHERE FISH_INFO.LENGTH = F.LENGTH
    ) AS FT 
    ON (FN.FISH_TYPE = FT.FISH_TYPE);
